pr: none
trigger: none

variables:
  azureSubscription: AzureDeveloperCollege

stages:
  - stage: Build
    displayName: Teardown SCM Common Infrastructure

    jobs:
      - template: jobs/teardown-scm-common.yaml
        parameters:
          artifactDropName: drop
          variableGroupName: Day8-VariableGroup-Dev
          environmentName: ADC-DAY8-SCM-DEV
          environmentServiceNameAzureRM: $(azureSubscription)
