apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  namespace: dapr-secrets
  name: keyvault
spec:
  type: secretstores.local.localsecretstore
  metadata:
  - name: secretsFile
    value: /Users/andreasmock/Projects/github/azuredevcollege/trainingdays/day8/apps/dotnetcore/Scm.Contacts/Adc.Scm.Api/components/localsecrets.json
  - name: nestedSeparator
    value: ":"